/* IMPORTS */
import { ReactJSXElement } from "@emotion/react/types/jsx-namespace";
import { Container, Paper, Typography } from "@mui/material";
import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";

/* TYPES */
interface PropsType {
  title: string;
  children: ReactJSXElement | ReactJSXElement[];
}

const ProtectedLayout = ({ title, children }: PropsType) => {
  /* STATE */

  /* HOOKS */
  const { data: session } = useSession();

  /* COMPONENT FUNCTIONS */

  /* JSX */
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <Container sx={{ padding: { xs: 1.5, sm: 2 } }}>
        {session ? (
          <>{children}</>
        ) : (
          <Paper>
            <Typography variant="h2">Restricted: Sign-in to access</Typography>
          </Paper>
        )}
      </Container>
    </>
  );
};

/* EXPORTS */
export default ProtectedLayout;
