/* IMPORTS */
import { ReactJSXElement } from "@emotion/react/types/jsx-namespace";
import { Container, Paper, Typography } from "@mui/material";
import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";

/* TYPES */
interface PropsType {
  title: string;
  children: ReactJSXElement | ReactJSXElement[];
}

const ProtectedLayout = ({ title, children }: PropsType) => {
  /* STATE */

  /* HOOKS */
  const { data: session } = useSession();

  /* COMPONENT FUNCTIONS */

  /* JSX */
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ padding: { xs: 1.5, sm: 2 } }}>
        {session ? (
          <>{children}</>
        ) : (
          <Paper>
            <Typography variant="h2">Restricted: Sign-in to access</Typography>
          </Paper>
        )}
      </Container>
    </>
  );
};

/* EXPORTS */
export default ProtectedLayout;
