/* IMPORTS */
import { ReactJSXElement } from "@emotion/react/types/jsx-namespace";
import { Container } from "@mui/material";
import Head from "next/head";
import React from "react";

/* TYPES */
interface PropsType {
  title: string;
  children: ReactJSXElement | ReactJSXElement[];
}

const PublicLayout = ({ title, children }: PropsType) => {
  /* STATE */

  /* HOOKS */

  /* COMPONENT FUNCTIONS */

  /* JSX */
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container sx={{ padding: { xs: 1.5, sm: 2 } }}>{children}</Container>
    </>
  );
};

/* EXPORTS */
export default PublicLayout;
