export const DUMMY_ROUTINES = [
  {
    name: "Justin Timberlake",
    routine: [
      { timeStart: "8am", timeEnd: "9am", activity: "Wake up" },
      { timeStart: "9am", timeEnd: "10am", activity: "Read" },
      { timeStart: "10am", timeEnd: "11am", activity: "Sing in the shower" },
      { timeStart: "11am", timeEnd: "12pm", activity: "Phone my parents" },
      { timeStart: "12pm", timeEnd: "1pm", activity: "Network" },
      { timeStart: "1pm", timeEnd: "2pm", activity: "Dabble with new lyrics" },
      { timeStart: "2pm", timeEnd: "3pm", activity: "Lunch" },
      { timeStart: "3pm", timeEnd: "4pm", activity: "Meditate" },
      { timeStart: "4pm", timeEnd: "5pm", activity: "Jog" },
      { timeStart: "5pm", timeEnd: "6pm", activity: "Read" },
    ],
  },
  {
    name: "Richard Gere",
    routine: [
      { timeStart: "8am", timeEnd: "9am", activity: "Wake up" },
      { timeStart: "9am", timeEnd: "10am", activity: "Read" },
      { timeStart: "10am", timeEnd: "11am", activity: "Sing in the shower" },
      { timeStart: "11am", timeEnd: "12pm", activity: "Phone my parents" },
      { timeStart: "12pm", timeEnd: "1pm", activity: "Network" },
      { timeStart: "1pm", timeEnd: "2pm", activity: "Dabble with new lyrics" },
      { timeStart: "2pm", timeEnd: "3pm", activity: "Lunch" },
      { timeStart: "3pm", timeEnd: "4pm", activity: "Meditate" },
      { timeStart: "4pm", timeEnd: "5pm", activity: "Jog" },
      { timeStart: "5pm", timeEnd: "6pm", activity: "Read" },
    ],
  },
  {
    name: "Miley Cyrus",
    routine: [
      { timeStart: "8am", timeEnd: "9am", activity: "Wake up" },
      { timeStart: "9am", timeEnd: "10am", activity: "Read" },
      { timeStart: "10am", timeEnd: "11am", activity: "Sing in the shower" },
      { timeStart: "11am", timeEnd: "12pm", activity: "Phone my parents" },
      { timeStart: "12pm", timeEnd: "1pm", activity: "Network" },
      { timeStart: "1pm", timeEnd: "2pm", activity: "Dabble with new lyrics" },
      { timeStart: "2pm", timeEnd: "3pm", activity: "Lunch" },
      { timeStart: "3pm", timeEnd: "4pm", activity: "Meditate" },
      { timeStart: "4pm", timeEnd: "5pm", activity: "Jog" },
      { timeStart: "5pm", timeEnd: "6pm", activity: "Read" },
    ],
  },
  {
    name: "Heugh Jackman",
    routine: [
      { timeStart: "8am", timeEnd: "9am", activity: "Wake up" },
      { timeStart: "9am", timeEnd: "10am", activity: "Read" },
      { timeStart: "10am", timeEnd: "11am", activity: "Sing in the shower" },
      { timeStart: "11am", timeEnd: "12pm", activity: "Phone my parents" },
      { timeStart: "12pm", timeEnd: "1pm", activity: "Network" },
      { timeStart: "1pm", timeEnd: "2pm", activity: "Dabble with new lyrics" },
      { timeStart: "2pm", timeEnd: "3pm", activity: "Lunch" },
      { timeStart: "3pm", timeEnd: "4pm", activity: "Meditate" },
      { timeStart: "4pm", timeEnd: "5pm", activity: "Jog" },
      { timeStart: "5pm", timeEnd: "6pm", activity: "Read" },
    ],
  },
  {
    name: "James Webb",
    routine: [
      { timeStart: "8am", timeEnd: "9am", activity: "Wake up" },
      { timeStart: "9am", timeEnd: "10am", activity: "Read" },
      { timeStart: "10am", timeEnd: "11am", activity: "Sing in the shower" },
      { timeStart: "11am", timeEnd: "12pm", activity: "Phone my parents" },
      { timeStart: "12pm", timeEnd: "1pm", activity: "Network" },
      { timeStart: "1pm", timeEnd: "2pm", activity: "Dabble with new lyrics" },
      { timeStart: "2pm", timeEnd: "3pm", activity: "Lunch" },
      { timeStart: "3pm", timeEnd: "4pm", activity: "Meditate" },
      { timeStart: "4pm", timeEnd: "5pm", activity: "Jog" },
      { timeStart: "5pm", timeEnd: "6pm", activity: "Read" },
    ],
  },
  {
    name: "Elon Musk",
    routine: [
      { timeStart: "8am", timeEnd: "9am", activity: "Wake up" },
      { timeStart: "9am", timeEnd: "10am", activity: "Read" },
      { timeStart: "10am", timeEnd: "11am", activity: "Sing in the shower" },
      { timeStart: "11am", timeEnd: "12pm", activity: "Phone my parents" },
      { timeStart: "12pm", timeEnd: "1pm", activity: "Network" },
      { timeStart: "1pm", timeEnd: "2pm", activity: "Dabble with new lyrics" },
      { timeStart: "2pm", timeEnd: "3pm", activity: "Lunch" },
      { timeStart: "3pm", timeEnd: "4pm", activity: "Meditate" },
      { timeStart: "4pm", timeEnd: "5pm", activity: "Jog" },
      { timeStart: "5pm", timeEnd: "6pm", activity: "Read" },
    ],
  },
];
